project:
  type: website
  output-dir: docs

website:
  title: "Davide Gentile"
  page-footer: "&copy; 2024 Davide Gentile. Built with Quarto"
  navbar:
    tools: 
      - icon: github
      - href: https://github.com
      
  sidebar:
    style: "docked"
    search: false
    contents:
        - text: "Welcome"
          href: index.qmd
        - href: work.qmd
          text: Portfolio
        - href: blog.qmd
          text: Notes
        - href: about.qmd
          text: About
 

format:
  html:
    theme: spacelab
    css: styles.css
    toc: true

editor: visual

