project:
  type: website
  output-dir: docs

website:
  #title: "Davide Gentile"
  page-footer: "&copy; 2024 Davide Gentile. Built with Quarto."
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      #- text: "Services"
        #href: services.qmd
      - text: "Projects"
        href: projects.qmd
      - text: "Blog"
        href: blog.qmd
      - text: "CV"
        href: docs/cv-Davide-Gentile.pdf
      #- text: "About"
        #href: about.qmd  
        
    #tools: 
      #- icon: linkedin
        #href: https://www.linkedin.com/in/davide-gentile-/
      #- icon: github
        #href: https://github.com/gentiled

 

format:
  html:
    theme: simplex
    linkcolor: "blue"
    css: styles.css
    toc: false

editor: visual

#best themes2: litera or simplex or spacelab

#best themes: flatly, default, litera, sandstone, simplex, spacelab
#flatly, default 8
# litera 6+
#sandstone, simplex, spacelab 8+
