project:
  type: website
  output-dir: docs

website:
  title: "Davide Gentile"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - work.qmd
      - courses.qmd
      - blog.qmd

format:
  html:
    theme: spacelab
    css: styles.css
    toc: true

editor: visual

