project:
  type: website
  output-dir: docs

website:
  #title: "Davide Gentile"
  page-footer: "&copy; 2024 Davide Gentile"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "About"
        href: about.qmd
      #- text: "Projects"
        #href: projects.qmd       
        
        
      #- text: "Sites"
        #menu: 
          #- text: "Services"
            #href: services.qmd
          #- text: "Projects"
            #href: projects.qmd
      - text: "Memos"
        href: blog.qmd
          #- text: "Courses"
            #href: courses.qmd
          #- text: "Academic papers"
            #href: publications.qmd 
      #- text: "Resume"
        #href: docs/Resume_Davide_Gentile.pdf
      #- text: "About"
        #href: about.qmd

    
      #- text: "Services"
        #href: services.qmd
      #- text: "Work"
        #href: projects.qmd
      #- text: "Publications"
        #href: publications.qmd 
        
        
    #tools: 
      #- icon: linkedin
        #href: https://www.linkedin.com/in/davide-gentile-/
      #- icon: github
        #href: https://github.com/gentiled

 

format:
  html:
    theme: simplex
    linkcolor: "blue"
    css: styles.css
    toc: false

editor: visual


#best themes: flatly, sandstone, simplex
#flatly 8
#sandstone, simplex 8+
