project:
  type: website
  output-dir: docs

website:
  title: "Davide Gentile"
  page-footer: "&copy; 2024 Davide Gentile. Built with {{< iconify simple-icons:quarto >}} [Quarto](https://quarto.org)"
  navbar:
    tools: 
      - icon: github
      - href: https://github.com
    left:
      - href: index.qmd
        text: home
      - text: sites
        menu: 
          - href: work.qmd
            text: projects
          - href: blog.qmd
            text: posts
          - href: research.qmd
            text: research
      - href: about.qmd    # Add href here
        text: about
      - href: resume.pdf
        text: resume

  sidebar:
    - title: "Sites"
      style: "docked"
      background: light
      contents:
        - href: work.qmd
        - href: blog.qmd
        - href: research.qmd
 


format:
  html:
    theme: spacelab
    css: styles.css
    toc: true

editor: visual

