project:
  type: website
  output-dir: docs

website:
  title: "Davide Gentile"
  page-footer: "&copy; 2024 Davide Gentile. Built with Quarto"
  navbar:
    tools: 
      - icon: github
        href: https://github.com
      #- icon: fa-google-scholar
        #href: https://github.com

      
  sidebar:
    style: "docked"
    search: false
    contents:
    
        - text: "Home"
          href: index.qmd
        - href: work.qmd
          text: Work
        - href: blog.qmd
          text: Thoughts
        - href: about.qmd
          text: About
 

format:
  html:
    theme: spacelab
    css: styles.css
    toc: true

editor: visual

