project:
  type: website
  output-dir: docs

website:
  title: "Human Factors & AI Consulting"
  page-footer: "&copy; 2024 Davide Gentile. Built with Quarto."
  navbar:
    right:
      - text: "Home"
        href: index.qmd
      - text: "Services"
        href: services.qmd
      - text: "Portfolio"
        href: projects.qmd
      #- text: "Blog"
        #href: blog.qmd
      - text: "About"
        href: about.qmd
        
    #tools: 
      #- icon: linkedin
        #href: https://www.linkedin.com/in/davide-gentile-/
      #- icon: github
        #href: https://github.com/gentiled

 

format:
  html:
    theme: default
    css: styles.css
    toc: true

editor: visual

#best themes: flatly, default, litera, sandstone, simplex, spacelab
#flatly, default 8
# litera 6+
#sandstone, simplex, spacelab 8+
