project:
  type: website
  output-dir: docs

website:
  title: "Davide Gentile"
  page-footer: "&copy; 2024 Davide Gentile. Built with Quarto"
  navbar:
    tools: 
      - icon: github
      - href: https://github.com
  sidebar:
    style: "docked"
    search: true
    contents:
        - href: work.qmd
          text: Projects
        - href: blog.qmd
          text: Publications
        - href: research.qmd
          text: Teaching
 

format:
  html:
    theme: spacelab
    css: styles.css
    toc: true

editor: visual

