project: 
  type: website
  output-dir: docs
  
website: 
  page-navigation: true
  title: "Making sharable documents with Quarto" 
  site-url: "https://gentiled.github.io" 
  repo-url: https://github.com/gentiled.github.io 
  repo-actions: [edit, issue]
  
  page-footer:
    right: "This page is built with ❤️ and [Quarto](https://quarto.org/)."
    left: "&copy; CC-By Davide Gentile, 2023"
    
  sidebar:
    logo: "images/.png"
    pinned: true
    align: center
    tools: 
      - icon: github
        href: https://github.com/
        text: "Quarto website tutorial"
       

    style: "docked"
    search: false
    collapse-level: 1
    contents:
      - href: index.qmd
        text: Welcome
      - explore.qmd
      - section: quarto-workflows/index.qmd
        contents: 
          - quarto-workflows/browser.md
          - quarto-workflows/rstudio.qmd
          - quarto-workflows/jupyter.md 
      - learning-more.qmd
      - href: transition-from-rmarkdown.qmd
        text: Transition from Rmd


format:
  html:
    theme:
      light: [cosmo, theme.scss] # from https://github.com/sta210-s22/website/blob/main/_quarto.yml
      dark: [cosmo, theme-dark.scss]
    code-copy: true
    code-overflow: wrap
    toc: true


filters:
  - include-files.lua
  - quarto

  
