project:
  type: website
  output-dir: docs

website:
  title: "Davide Gentile"
  navbar:
    left:
      - href: index.qmd
        text: home
      - about.qmd
      - href: resume.pdf
        text: resume

format:
  html:
    theme: spacelab
    css: styles.css
    toc: true

editor: visual

