project:
  type: website
  output-dir: docs

website:
  title: "Davide Gentile"
  page-footer: "&copy; 2024 Davide Gentile. Built with Quarto and RStudio."
  navbar:
    right:
      - text: "Portfolio"
        href: projects.qmd
      - text: "Blog"
        href: blog.qmd
      - text: "About"
        href: about.qmd
        
    tools: 
      - icon: linkedin
        href: https://www.linkedin.com/in/davide-gentile-/
      - icon: github
        href: https://github.com/gentiled

 

format:
  html:
    theme: spacelab
    css: styles.css
    toc: true

editor: visual

