project:
  type: website
  output-dir: docs

website:
  title: "Davide Gentile"
  sidebar:
    style: "floating"
    search: false
    #background: secondary
    contents:
      - text: "About"
        href: index.qmd
      - text: "Projects"
        href: work.qmd
      #- text: "CV"
        #href: notes.qmd
      - text: "Blog"
        href: notes.qmd
    #right:
      #- icon: linkedin
        #href: https://www.linkedin.com/in/davide-gentile-/

  page-footer: "© 2025 Davide Gentile"
  


format:
  html:
    theme: [cosmo]
    #css: styles.css
    toc: false
    #page-layout: full