project:
  type: website
  output-dir: docs

website:
  title: ""
  navbar:
    background: light
    search: false
    left:
      - text: "Home"
        href: index.qmd
      - text: "Work"
        href: work.qmd
      #- text: "Notes"
        #href: notes.qmd
      - text: "About"
        href: about.qmd
    right:
      - icon: linkedin
        href: https://linkedin.com/in/yourprofile

  page-footer: "© 2025 Davide Gentile. All rights reserved."


format:
  html:
    theme: [cosmo]
    #css: styles.css
    toc: false
    #page-layout: full