project:
  type: website
  output-dir: docs

website:
  sidebar:
    search: false
    left:
      - href: index.qmd
        text: Home
      - favourites.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
