project:
  type: website
  output-dir: docs

website:
  title: "Davide Gentile"
  page-footer: "&copy; 2024 Davide Gentile"
  navbar:
    left:
      - text: "Home"
        href: index.qmd

      - text: "Services"
        href: services.qmd 
      - text: "Projects"
        href: projects.qmd
      - text: "About"
        href: about.qmd
        
      #- text: "Case studies"
        #href: projects.qmd
        
      #- text: "Resources"
        #menu: 

          #- text: "Insights"
            #href: blog.qmd
            
      #- text: "Publications"
        #href: publications.qmd
            
          #- text: "Guides & Tools"
            #href: guides.qmd
      
      #- text: "Services"
        #menu: 
          #-  text: "Interface Design"
             #href: services.qmd
          #-  text: "Human-AI Evaluation"
             #href: services.qmd
          #-  text: "Training"
             #href: blog.qmd
          #- text: "Courses"
            #href: courses.qmd
          #- text: "Academic papers"
            #href: publications.qmd 
      #- text: "Posts"
        #href: blog.qmd           
        
      #- text: "Resume"
        #href: docs/Resume_Davide_Gentile.pdf
      #- text: "About"
        #href: about.qmd

      #- text: "Contact"
        #href: contact.qmd
      #- text: "Insights"
        #href: blog.qmd 
        
        
    #tools: 
      #- icon: linkedin
        #href: https://www.linkedin.com/in/davide-gentile-/
      #- icon: github
        #href: https://github.com/gentiled

 

format:
  html:
    theme: simplex
    linkcolor: "darkblue"
    css: styles.css
    toc: false

editor: visual

# https://bootswatch.com/

#best themes: flatly, sandstone, simplex
#flatly 8
#sandstone, simplex 8+
