project: 
  type: website
  output-dir: docs
  
website: 
  page-navigation: true
  title: "Davide Gentile" 
  site-url: "https://gentiled.github.io" 
  repo-url: https://github.com/gentiled.github.io 
  repo-actions: [edit, issue]
  
  page-footer:
    right: "This page is built with [Quarto](https://quarto.org/)."
    left: "&copy; CC-By Davide Gentile, 2023"
    
  sidebar:
    logo: "images/.png"
    pinned: true
    align: center
    tools: 
      - icon: linkedin
        href: https://github.com/gentiled.github.io
        text: "LinkedIn profile"
      - icon: github
        href: https://github.com/gentiled.github.io
        text: "GitHub repository"
       

    style: "docked"
    search: false
    collapse-level: 1
    contents:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: portfolio.qmd
        text: Portfolio
      - href: blog.qmd
        text: Thoughts
      - href: https://drive.google.com/file/d/1bOEEos4XTVu6zrWAszAfdLtUsGF6c2TF/view?usp=sharing
        text: Resume


format:
  html:
    #theme:
    #  light: [cosmo, theme.scss] # from https://github.com/sta210-s22/website/blob/main/_quarto.yml
    #  dark: [cosmo, theme-dark.scss]
    code-copy: true
    code-overflow: wrap
    toc: true


filters:
  - include-files.lua
  - quarto

  
