---
title: "Resume"
subtitle: "Email: gentiledv at gmail dot com"
---

+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------+
| ### Work                                                                                                                                                                                          | **Expertise**                  |
|                                                                                                                                                                                                   |                                |
| **Postdoctoral researcher** - University of Toronto                                                                                                                                               | Statistics                     |
|                                                                                                                                                                                                   |                                |
| 09/2024 -- present                                                                                                                                                                                | Design of experiments          |
|                                                                                                                                                                                                   |                                |
| -   I lead the experimental and analytical teams at the Cognitive Engineering Lab on projects funded by NSERC\* and CNSC\*\* focused on remote monitoring and control of small modular reactors.  | Machine learning               |
|                                                                                                                                                                                                   |                                |
| -   Between 2019 and 2024 I was PhD researcher and teaching assistant in statistical programming and human factors engineering.                                                                   | Human-subjects research        |
|                                                                                                                                                                                                   |                                |
| -   My PhD focused on designing and evaluating explainable AI displays to support human decisions and performance in safety-critical work environments.                                           | Causal inference               |
|                                                                                                                                                                                                   |                                |
| **Data science consultant** - Armilla AI                                                                                                                                                          | Prototyping                    |
|                                                                                                                                                                                                   |                                |
| 01/2024 - 06/2024                                                                                                                                                                                 | Cross-functional collaboration |
|                                                                                                                                                                                                   |                                |
| I worked part-time in this Toronto-based startup,                                                                                                                                                 | **Tools**                      |
| where I have developed risk assessment frameworks to evaluate predictive and                                                                                                                      |                                |
| generative models across different dimensions, including system performance and                                                                                                                   | R, RStudio                     |
| model bias.                                                                                                                                                                                       |                                |
|                                                                                                                                                                                                   | Python                         |
| **Research intern** - Ericsson                                                                                                                                                                    |                                |
|                                                                                                                                                                                                   | Quarto                         |
| 10/2020 - 06/2024                                                                                                                                                                                 |                                |
|                                                                                                                                                                                                   | Books, papers                  |
| I led the human-subjects evaluation of a machine                                                                                                                                                  |                                |
| learning software designed by my team to support the productivity and performance of Ericsson\'s data scientists.                                                                                 | **Languages**                  |
|                                                                                                                                                                                                   |                                |
|                                                                                                                                                                                                   | Italian                        |
|                                                                                                                                                                                                   |                                |
|                                                                                                                                                                                                   | English                        |
|                                                                                                                                                                                                   |                                |
|                                                                                                                                                                                                   | Latin                          |
|                                                                                                                                                                                                   |                                |
|                                                                                                                                                                                                   | Basic Spanish and French       |
+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------+
