---
title: "Simpson's Paradox"
---

```{r}
# load the tidyverse
library(tidyverse)
library(hrbrthemes)    # ipsum theme for ggplot2 charts
library(patchwork)     # combine charts together
library(DT)            # interactive tables
library(knitr)         # static table with the kable() function
library(plotly)        # interactive graphs
```

```{r}
install.packages("palmerpenguins")
library(palmerpenguins)
data(package = 'palmerpenguins')
head(penguins)
head(penguins_raw)
```

```{r}
penguin_df<- 
  palmerpenguins::penguins %>%
  na.omit()


DT::datatable(head(penguin_df))
```

```{r}
penguin_df %>%
  ggplot(aes(x=bill_length_mm, y=bill_depth_mm)) +
  geom_point() + 
  labs(x="Length", y="Depth", title="Bill Depth as a function of Bill Length") +
  theme_classic()
```

```{r}
penguin_df %>%
  ggplot(aes(x=bill_length_mm, y=bill_depth_mm, 
             color=species)) +
  geom_point() + 
  labs(x="Length", y="Depth", title="Bill Depth as a function of Bill Length") +
  theme_classic()
```

```{r}
data(penguins, package="palmerpenguins")
```

```{r}
peng <- penguins_raw %>%
  mutate(species = as.factor(Species),
         island = as.factor(Island),
         sex = as.factor(substr(Sex,1,1))) %>%
  filter(!is.na("Culmen Depth (mm)"))
```

```{r}
library(car)
library(ggbiplot)
library(GGally)
```

```{r}
scatterplotMatrix(~ `Culmen Length (mm)` + `Culmen Depth (mm)` + `Flipper Length (mm)` + `Body Mass (g)` | Species,
                  data=peng,
                  ellipse=list(levels=0.68),
                  col = scales::hue_pal()(3),
                  legend=list(coords="bottomright"))
```

https://rpubs.com/friendly/penguin-biplots
